function(set_common_properties FMMA_TARGET)
  target_compile_options(${FMMA_TARGET} PRIVATE -g -O3 -Wall -Wextra -fPIC)

  find_package(OpenMP)
  if(OpenMP_CXX_FOUND)
    add_definitions(-DOPENMP_FOUND)
    if(FMMA_CMAKE_DEBUG_FLAG)
      message(STATUS "Found OpenMP")
    endif()
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
    target_compile_options(${FMMA_TARGET} PRIVATE -fopenmp)
    target_link_libraries(${FMMA_TARGET} PRIVATE OpenMP::OpenMP_CXX)
  else()
    if(FMMA_CMAKE_DEBUG_FLAG)
      message(STATUS "Not Found OpenMP")
    endif()
  endif()
endfunction()
