name: github-actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Steup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc
          cmake: true
          make: true

      - name: hello world
        run: echo Hello World!!

      - name: pwd
        run: pwd

      - name: ls
        run: ls

      - name: build
        run: |
          ls
          mkdir build
          cd build
          cmake ../.
          make
