name: github-actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Steup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc
          cmake: true
          make: true

      - name: build
        run: |
          mkdir build
          cd build
          cmake ../.
          make
