name: benchmark
on: [push]
jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc
          cmake: true
          make: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: build
        run: |
          cmake -Bbuild
          cmake --build build

      - name: benchmark
        run: |
          cd benchmark
          cmake -Bbuild
          cmake --build build
          bash run_benchmark.sh
          mkdir benchmark
          cp *.csv benchmark/
          cd ..

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Pip python
        run: |
          pip install pandas
          pip install matplotlib

      - name: benchmark image
        run: |
          cd benchmark
          python3 plot_time.py
          cp *.png benchmark/
          cd ..

      - name: Upload Benchmark
        uses: actions/upload-artifact@v4
        with:
          name: benchmark results
          path: benchmark/benchmark/*.csv

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
