name: tutorial
on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc
          cmake: true
          make: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: build
        run: |
          cmake -B build
          cmake --build build
          sudo cmake --install build


      - name: tutorial
        run: |
          cd tutorial
          cmake -B build
          cmake --build build
